server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Handle React routing — send all requests to index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # API proxy — forward /api requests to backend
    location /api {
        proxy_pass http://backend-service:5001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}


# LOCAL TEST
# server {
#     listen 80;
#     server_name _;

#     root /usr/share/nginx/html;
#     index index.html;

#     # Handle React routing — send all requests to index.html
#     location / {
#         try_files $uri $uri/ /index.html;
#     }
# }